image: registry.gitlab.com/tobifinn/tf-assimilate

variables:
    SPHINX_DOC_DIR: sphinx-doc
    COVERAGE_STATIC_DIR: coverage-report
    PAGES_DIR: public
    DIST_DIR: dist
    DEV_ENV_TEST: tfassim-dev-test
    ENV_TEST: tfassim-test

stages:
    - install
    - test
    - package
    - deploy

before_script:
    - source activate tfassim-dev

build-docker:
    stage: install
    image: docker:latest
    variables:
        DOCKER_DRIVER: overlay
    services:
        - docker:dind
    before_script: []
    script:
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $DOCKER_REGISTRY
        - docker build -t $DOCKER_REGISTRY/<PROJECT-GROUP>/<PROJECT-NAME> .
        - docker push $DOCKER_REGISTRY/<PROJECT-GROUP>/<PROJECT-NAME>
    when: manual

check-envs:
    stage: install
    before_script:
        - "conda remove --name $ENV_TEST --all || :"
        - "conda remove --name $DEV_ENV_TEST --all || :"
    after_script:
        - "conda remove --name $ENV_TEST --all || :"
        - "conda remove --name $DEV_ENV_TEST --all || :"
    script:
        - echo ${pwd}
        - ls -al
        - conda env create -f environment.yml --name $ENV_TEST
        - conda env create -f dev_environment.yml --name $DEV_ENV_TEST

install-tfassim:
    stage: install
    script:
        - python setup.py install

coverage:
    stage: test
    script:
        - coverage run setup.py test
        - coverage report
        - coverage html
        - mv htmlcov/ $COVERAGE_STATIC_DIR
    coverage: '/TOTAL.*\s+(\d+\%)/'
    artifacts:
        paths:
            - $COVERAGE_STATIC_DIR
        expire_in: 1 week

codequality:
    stage: test
    image: docker:latest
    before_script: []
    variables:
        DOCKER_DRIVER: overlay
    services:
        - docker:dind
    script:
        - docker pull codeclimate/codeclimate:0.69.0
        - docker run --env CODECLIMATE_CODE="$PWD" --volume "$PWD":/tfassim --volume /var/run/docker.sock:/var/run/docker.sock --volume /tmp/cc:/tmp/cc codeclimate/codeclimate:0.69.0 analyze -f json > codeclimate.json || true
    artifacts:
        paths:
            - codeclimate.json
        expire_in: 1 week

sphinx:
    stage: package
    script:
        - make docs
        - mv docs/build/html $SPHINX_DOC_DIR
    artifacts:
        paths:
            - $SPHINX_DOC_DIR
        expire_in: 1 week

dist:
    stage: package
    dependencies: []
    script:
        - make dist
    artifacts:
        paths:
            - dist/*
        expire_in: 1 week

pages:
    before_script: []
    stage: deploy
    dependencies:
        - sphinx
        - coverage
    script:
        - rm -rf $PAGES_DIR/ # make sure there is not pages dir
        - mv $SPHINX_DOC_DIR $PAGES_DIR/ # sphinx doc is index page
        - mv $COVERAGE_STATIC_DIR $PAGES_DIR/ # put coverage report inside
    artifacts:
        paths:
            - $PAGES_DIR/
    only:
        - dev

pypi-upload:
    stage: deploy
    environment:
        name: production
        url: https://pypi.org/project/tf-assimilate/
    script:
        - twine upload -u "$PYPI_USERNAME" -p "$PYPI_PASSWORD" dist/*
    dependencies:
        - dist
    only:
        - master

pypi-test-upload:
    stage: deploy
    environment:
        name: testing
        url: https://test.pypi.org/project/tf-assimilate/
    script:
        - >
            twine upload -u "$PYPI_USERNAME" -p "$PYPI_PASSWORD"
            --repository-url https://test.pypi.org/legacy/ dist/*
    dependencies:
        - dist
    only:
        - tag
