image: registry.gitlab.com/tobifinn/tf-assimilate

variables:
    SPHINX_DOC_DIR: sphinx-doc
    COVERAGE_STATIC_DIR: coverage-report
    PAGES_DIR: public
    DIST_DIR: radar_software/dist

stages:
    - install
    - test
    - deploy

before_script:
    - source activate tfassim-dev


install-tfassim:
    stage: install
    script:
        - python setup.py install

coverage:
    stage: test
    script:
        - coverage run setup.py test
        - coverage report
        - coverage html
        - mv htmlcov/ $COVERAGE_STATIC_DIR
    coverage: '/TOTAL.*\s+(\d+\%)/'
    artifacts:
        paths:
            - $COVERAGE_STATIC_DIR
        expire_in: 1 week

