name: tfassim-dev
channels:
    - conda-forge
dependencies:
    - python=3.6
    - setuptools
    - coverage
    - sphinx
    - sphinx_rtd_theme
    - xarray
    - numpy
    - scipy
    - tensorflow
    - pip:
        - twine
