name: tfassim-dev
channels:
    - conda-forge
dependencies:
    - python=3.6
    - setuptools
    - coverage
    - sphinx
    - xarray
    - numpy
    - scipy
    - tensorflow
    - pip
    - pip:
        twine
